!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!                                                         ! 
!    FILE: inirea.F90                                     !
!    CONTAINS: subroutine inirea                          !
!                                                         ! 
!    PURPOSE: Initialization routine. Reads in a flow     !
!     snapshot generated by a previous simulation, and    !
!     interpolates to the current grid if necessary       !
!                                                         !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      subroutine ReadFlowField
      use mpih
      use decomp_2d
      use local_arrays
      use param
      IMPLICIT NONE
      character*70 :: filnam1,dsetname
      integer :: ihist
      integer :: n1om,n2om,n3o,n2o,n1o
      integer :: xs2og,xe2og,xs3og,xe3og
      integer :: istro3
      integer (kind=MPI_ADDRESS_KIND) :: extent,lb
      real :: stro3
      real :: intinfo(1:4)
      real, allocatable, dimension(:,:,:) :: densold,q2old,q3old,q1old
      logical :: fexist
      
!EP   Reading old grid information by rank0
      filnam1 = trim('continua_master.h5')

      inquire(file=filnam1,exist=fexist)
      if (.not.fexist) then 
        write(*,*) 'Continuation files not found'
        stop
      end if

      if (nrank .eq. 0) then
       dsetname = trim('n1')
       call HdfSerialReadIntScalar(dsetname,filnam1,n1o)
       dsetname = trim('n2')
       call HdfSerialReadIntScalar(dsetname,filnam1,n2o)
       dsetname = trim('n3')
       call HdfSerialReadIntScalar(dsetname,filnam1,n3o)
       dsetname = trim('time')
       call HdfSerialReadRealScalar(dsetname,filnam1,time)
       dsetname = trim('istr3')
       call HdfSerialReadIntScalar(dsetname,filnam1,istro3)
       dsetname = trim('str3')
       call HdfSerialReadRealScalar(dsetname,filnam1,stro3)
      endif
      
      call MpiBarrier
      call MpiBcastInt(n1o)
      call MpiBcastInt(n2o)
      call MpiBcastInt(n3o)
      call MpiBcastReal(istro3)
      call MpiBcastReal(stro3)
      call MpiBcastReal(time)
      
!EP   Check whether grid specifications have been updated
      if(n2o.ne.n2.or.n3o.ne.n3.or.n1o.ne.n1 &
       .or.istro3.ne.istr3.or.stro3.ne.str3) then
      if(nrank.eq.0) write(*,*) "Interpolating new grid"
      if(n1.gt.n1o*2.or.n2.gt.n2o*2.or.n3.gt.n3o*2) then
      if(nrank.eq.0) write(*,*) "New grid resolution cannot be more ", &
       "than twice the old resolution"
      call MPI_ABORT(MPI_COMM_WORLD,1,ierr)
      endif

      n1om = n1o - 1
      n2om = n2o - 1
      
      intinfo(1) = istro3
      intinfo(2) = stro3

      call MPI_BARRIER(MPI_COMM_WORLD,ierr)

      xs2og = floor(real(xstart(2)*n2om/n2m))
      xe2og = ceiling(real(xend(2)*n2om/n2m))
      xs3og = floor(real(xstart(3)*n1om/n1m))
      xe3og = ceiling(real(xend(3)*n1om/n1m))

      xs2og = max(xs2og,1)
      xe2og   = min(xe2og,n2om)
      xs3og = max(xs3og,1)
      xe3og   = min(xe3og,n1om)
      
      lb=0
      call MPI_TYPE_GET_EXTENT(MPI_DOUBLE_PRECISION,lb,extent,ierr)
!EP   dens
      allocate(densold(0:n3o+1,xs2og-1:xe2og+1,xs3og-1:xe3og+1))
      
      call hdf_read(n1o,n2o,n3o,xs2og,xe2og, &
       xs3og,xe3og,4,densold(1:n3o,xs2og-1:xe2og+1,xs3og-1:xe3og+1))

      call interp(densold,dens(1:n3,xstart(2):xend(2),xstart(3):xend(3)) &
       ,n1o,n2o,n3o,istro3,stro3,4,xs2og,xe2og,xs3og,xe3og)

      deallocate(densold)

!EP   q1
      allocate(q1old(0:n3o+1,xs2og-1:xe2og+1,xs3og-1:xe3og+1))
      
      call hdf_read(n1o,n2o,n3o,xs2og,xe2og, &
       xs3og,xe3og,1,q1old(1:n3o,xs2og-1:xe2og+1,xs3og-1:xe3og+1))

      call interp(q1old,q1(1:n3,xstart(2):xend(2),xstart(3):xend(3)) &
       ,n1o,n2o,n3o,istro3,stro3,1,xs2og,xe2og,xs3og,xe3og)

      deallocate(q1old)

!EP   q2
      allocate(q2old(0:n3o+1,xs2og-1:xe2og+1,xs3og-1:xe3og+1))
      
      call hdf_read(n1o,n2o,n3o,xs2og,xe2og, &
     & xs3og,xe3og,2,q2old(1:n3o,xs2og-1:xe2og+1,xs3og-1:xe3og+1))

      call interp(q2old,q2(1:n3,xstart(2):xend(2),xstart(3):xend(3)) &
     & ,n1o,n2o,n3o,istro3,stro3,2,xs2og,xe2og,xs3og,xe3og)

      deallocate(q2old)

!EP   q3
      allocate(q3old(0:n3o+1,xs2og-1:xe2og+1,xs3og-1:xe3og+1))
      
      call hdf_read(n1o,n2o,n3o,xs2og,xe2og, &
     & xs3og,xe3og,3,q3old(1:n3o,xs2og-1:xe2og+1,xs3og-1:xe3og+1))

      call interp(q3old,q3(1:n3,xstart(2):xend(2),xstart(3):xend(3)) &
     & ,n1o,n2o,n3o,istro3,stro3,3,xs2og,xe2og,xs3og,xe3og)

      deallocate(q3old)

      else

!EP   One to one HDF read
      call hdf_read(n1,n2,n3,xstart(2),xend(2) &
     & ,xstart(3),xend(3),4,dens)
      call hdf_read(n1,n2,n3,xstart(2),xend(2) &
     & ,xstart(3),xend(3),1,q1)
      call hdf_read(n1,n2,n3,xstart(2),xend(2) &
     & ,xstart(3),xend(3),2,q2)
      call hdf_read(n1,n2,n3,xstart(2),xend(2) &
     & ,xstart(3),xend(3),3,q3)

      endif

      if (ireset.eq.1) then                                             
       ihist=0                                                          
      time=0.
      endif                                                             

!EP   Increase the maximum simulation time by the end time in the
!continuation files
        tmax = tmax + time

      return                                                            
      end                                                               
!                                                                       
