!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!                                                         ! 
!    FILE: inirea.F90                                     !
!    CONTAINS: subroutine inirea                          !
!                                                         ! 
!    PURPOSE: Initialization routine. Reads in a flow     !
!     snapshot generated by a previous simulation, and    !
!     interpolates to the current grid if necessary       !
!                                                         !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      subroutine ReadFlowField
      use mpih
      use decomp_2d
      use local_arrays
      use param
      IMPLICIT NONE
      character*70 :: filnam1,dsetname
      integer :: ihist
      integer :: nzom,nyom,nxo,nyo,nzo
      integer :: xs2og,xe2og,xs3og,xe3og
      integer :: istro3
      integer (kind=MPI_ADDRESS_KIND) :: extent,lb
      real :: stro3
      real :: intinfo(1:4)
      real, allocatable, dimension(:,:,:) :: tempold,q2old,q3old,q1old
      logical :: fexist
      
!EP   Reading old grid information by rank0
      filnam1 = trim('continua_master.h5')

      inquire(file=filnam1,exist=fexist)
      if (.not.fexist) then 
        write(*,*) 'Continuation files not found'
        stop
      end if

      if (nrank .eq. 0) then
       dsetname = trim('nx')
       call HdfSerialReadIntScalar(dsetname,filnam1,nxo)
       dsetname = trim('ny')
       call HdfSerialReadIntScalar(dsetname,filnam1,nyo)
       dsetname = trim('nz')
       call HdfSerialReadIntScalar(dsetname,filnam1,nzo)
       dsetname = trim('time')
       call HdfSerialReadRealScalar(dsetname,filnam1,time)
       dsetname = trim('istr3')
       call HdfSerialReadIntScalar(dsetname,filnam1,istro3)
       dsetname = trim('str3')
       call HdfSerialReadRealScalar(dsetname,filnam1,stro3)
      endif
      
      call MpiBarrier
      call MpiBcastInt(nxo)
      call MpiBcastInt(nyo)
      call MpiBcastInt(nzo)
      call MpiBcastReal(istro3)
      call MpiBcastReal(stro3)
      call MpiBcastReal(time)
      
!EP   Check whether grid specifications have been updated
      if(nyo.ne.ny.or.nxo.ne.nx.or.nzo.ne.nz &
       .or.istro3.ne.istr3.or.stro3.ne.str3) then
      if(nrank.eq.0) write(*,*) "Interpolating new grid"
      if(nz.gt.nzo*2.or.ny.gt.nyo*2.or.nx.gt.nxo*2) then
      if(nrank.eq.0) write(*,*) "New grid resolution cannot be more ", &
       "than twice the old resolution"
      call MPI_ABORT(MPI_COMM_WORLD,1,ierr)
      endif

      nzom = nzo - 1
      nyom = nyo - 1
      
      intinfo(1) = istro3
      intinfo(2) = stro3

      call MPI_BARRIER(MPI_COMM_WORLD,ierr)

      xs2og = floor(real(xstart(2)*nyom/nym))
      xe2og = ceiling(real(xend(2)*nyom/nym))
      xs3og = floor(real(xstart(3)*nzom/nzm))
      xe3og = ceiling(real(xend(3)*nzom/nzm))

      xs2og = max(xs2og,1)
      xe2og   = min(xe2og,nyom)
      xs3og = max(xs3og,1)
      xe3og   = min(xe3og,nzom)
      
      lb=0
      call MPI_TYPE_GET_EXTENT(MPI_DOUBLE_PRECISION,lb,extent,ierr)
!EP   temp
      allocate(tempold(0:nxo+1,xs2og-1:xe2og+1,xs3og-1:xe3og+1))
      
      call hdf_read(nzo,nyo,nxo,xs2og,xe2og, &
       xs3og,xe3og,4,tempold(1:nxo,xs2og-1:xe2og+1,xs3og-1:xe3og+1))

      call interp(tempold,temp(1:nx,xstart(2):xend(2),xstart(3):xend(3)) &
       ,nzo,nyo,nxo,istro3,stro3,4,xs2og,xe2og,xs3og,xe3og)

      deallocate(tempold)

!EP   qx
      allocate(q1old(0:nxo+1,xs2og-1:xe2og+1,xs3og-1:xe3og+1))
      
      call hdf_read(nzo,nyo,nxo,xs2og,xe2og, &
       xs3og,xe3og,1,q1old(1:nxo,xs2og-1:xe2og+1,xs3og-1:xe3og+1))

      call interp(q1old,q1(1:nx,xstart(2):xend(2),xstart(3):xend(3)) &
       ,nzo,nyo,nxo,istro3,stro3,1,xs2og,xe2og,xs3og,xe3og)

      deallocate(q1old)

!EP   q2
      allocate(q2old(0:nxo+1,xs2og-1:xe2og+1,xs3og-1:xe3og+1))
      
      call hdf_read(nzo,nyo,nxo,xs2og,xe2og, &
     & xs3og,xe3og,2,q2old(1:nxo,xs2og-1:xe2og+1,xs3og-1:xe3og+1))

      call interp(q2old,q2(1:nx,xstart(2):xend(2),xstart(3):xend(3)) &
     & ,nzo,nyo,nxo,istro3,stro3,2,xs2og,xe2og,xs3og,xe3og)

      deallocate(q2old)

!EP   q3
      allocate(q3old(0:nxo+1,xs2og-1:xe2og+1,xs3og-1:xe3og+1))
      
      call hdf_read(nzo,nyo,nxo,xs2og,xe2og, &
     & xs3og,xe3og,3,q3old(1:nxo,xs2og-1:xe2og+1,xs3og-1:xe3og+1))

      call interp(q3old,q3(1:nx,xstart(2):xend(2),xstart(3):xend(3)) &
     & ,nzo,nyo,nxo,istro3,stro3,3,xs2og,xe2og,xs3og,xe3og)

      deallocate(q3old)

      else

!EP   One to one HDF read
      call hdf_read(nz,ny,nx,xstart(2),xend(2) &
     & ,xstart(3),xend(3),4,temp)
      call hdf_read(nz,ny,nx,xstart(2),xend(2) &
     & ,xstart(3),xend(3),1,q1)
      call hdf_read(nz,ny,nx,xstart(2),xend(2) &
     & ,xstart(3),xend(3),2,q2)
      call hdf_read(nz,ny,nx,xstart(2),xend(2) &
     & ,xstart(3),xend(3),3,q3)

      endif

      if (ireset.eq.1) then                                             
       ihist=0                                                          
      time=0.
      endif                                                             

!EP   Increase the maximum simulation time by the end time in the
!continuation files
        tmax = tmax + time

      return                                                            
      end                                                               
!                                                                       
